name: Build Backend app and deploy

#defaults:
#  run:
#    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
      - backend 

jobs:
  Get_Dependencies:
    name: Build Backend
   # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: |
          sudo apt-get update && sudo apt-get -y install maven

  Test:
    name: Test Backend
   # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: build Backend
      run: |
          cd backend
          mvn clean test
    needs: [Get_Dependencies]

  Buid_Java:
    name: Build Java Backend
   # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: build backend
      run: |
          cd backend
          mvn clean package
    needs: [Test]

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}
      
      - name: open folder
        run: cd backend

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/11-jre:${{ github.sha }}
#            docker.pkg.github.com/${{ github.repository }}/octo-image:${{ github.event.release.tag_name }}
    needs: [Buid_Java]